apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-library-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-library-management
  template:
    metadata:
      labels:
        app: php-library-management
    spec:
      containers:
      - name: php-library-management
        image: chaitanyah3/library-management-system:latest
        imagePullPolicy: Never  # Use locally built image in Minikube
        ports:
        - containerPort: 80
