apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
      - name: library-management
        image: library-management-system:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: library-management-service
spec:
  type: NodePort
  selector:
    app: library-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
