apiVersion: v1
kind: Service
metadata:
  name: php-library-management-service
spec:
  type: NodePort
  selector:
    app: php-library-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
